{ lib, ... }:
{
  nixpkgs.overlays = [ (self: super: { buildLinux = x: super.buildLinux ({ ignoreConfigErrors = true; } // x); } ) ];

  boot.initrd.availableKernelModules = lib.mkForce [
    "ahci"
    "aic79xx"
    "aic7xxx"
    "arcmsr"
    "uas"
    "sdhci_pci"
    "ohci1394"
    "sbp2"
    "virtio_net"
    "virtio_pci"
    "virtio_blk"
    "virtio_scsi"
    "virtio_balloon"
    "virtio_console"
    "vsock"
    "squashfs"
    "iso9660"
    "uas"
    "overlay"
    "ext2"
    "ext3"
    "ext4"
    "ahci"
    "sd_mod"
    "mmc_block"
    "uhci_hcd"
    "ehci_hcd"
    "ehci_pci"
    "ohci_hcd"
    "ohci_pci"
    "xhci_hcd"
    "xhci_pci"
    "usbhid"
    "hid_generic"
    "hid_lenovo"
    "hid_apple"
    "hid_roccat"
    "hid_logitech_hidpp"
    "hid_logitech_dj"
    "hid_microsoft"
    "pcips2"
    "atkbd"
    "i8042"
    "rtc_cmos"
  ];

  boot.kernelPatches = [ {
    name = "fast-build";
    patch = null;
    extraConfig = ''
        PGTABLE_LEVELS 4
        X86_EXTENDED_PLATFORM n
        X86_AMD_PLATFORM_DEVICE n
        MCORE2 y
        X86_INTEL_USERCOPY y
        X86_USE_PPRO_CHECKSUM y
        X86_P6_NOP y
        NR_CPUS 8
        X86_MCE_AMD n
        PERF_EVENTS_AMD_POWER n
        MICROCODE_AMD n
        X86_5LEVEL n
        AMD_NUMA n
        X86_PMEM_LEGACY n
        WQ_POWER_EFFICIENT_DEFAULT y
        ENERGY_MODEL y
        X86_ACPI_CPUFREQ_CPB n
        X86_POWERNOW_K8 n
        X86_AMD_FREQ_SENSITIVITY n
        X86_SPEEDSTEP_CENTRINO n
        X86_P4_CLOCKMOD n
        KVM_AMD n
        NET_KEY n
        TIPC n
        ATM n
        DECNET n
        LLC2 n
        ATALK n
        X25 n
        LAPB n
        PHONET n
        BATMAN_ADV n
        OPENVSWITCH n
        CAN n
        CAIF n
        NFC n
        PCCARD m
        RAPIDIO n
        GNSS n
        PARPORT n
        BLK_DEV_FD n
        BLK_DEV_UMEM n
        BLK_DEV_SKD n
        CDROM_PKTCDVD n
        BLK_DEV_RBD n
        BLK_DEV_RSXX n
        AD525X_DPOT n
        IBM_ASM n
        PHANTOM n
        HP_ILO n
        C2PORT n
        ECHO n
        HABANA_AI n
        FIREWIRE m
        EQUALIZER n
        ARCNET n
        FDDI n
        HIPPI n
        NET_SB1000 n
        USB_CATC n
        USB_KAWETH n
        USB_PEGASUS n
        USB_RTL8150 n
        USB_RTL8152 n
        USB_LAN78XX n
        USB_NET_AX8817X n
        USB_NET_AX88179_178A n
        USB_NET_CDC_EEM n
        USB_NET_CDC_NCM n
        USB_NET_HUAWEI_CDC_NCM n
        USB_NET_CDC_MBIM n
        USB_NET_DM9601 n
        USB_NET_SR9700 n
        USB_NET_SR9800 n
        USB_NET_SMSC75XX n
        USB_NET_SMSC95XX n
        USB_NET_GL620A n
        USB_NET_NET1080 n
        USB_NET_PLUSB n
        USB_NET_MCS7830 n
        USB_NET_CDC_SUBSET n
        USB_NET_ZAURUS n
        USB_NET_CX82310_ETH n
        USB_NET_KALMIA n
        USB_NET_QMI_WWAN n
        USB_HSO n
        USB_NET_INT51X1 n
        USB_IPHETH n
        USB_SIERRA_NET n
        USB_VL600 n
        USB_NET_CH9200 n
        USB_NET_AQC111 n
        USB_RTL8153_ECM n
        WLAN_VENDOR_ADMTEK n
        WLAN_VENDOR_ATH n
        WLAN_VENDOR_ATMEL n
        WLAN_VENDOR_BROADCOM n
        WLAN_VENDOR_CISCO n
        WLAN_VENDOR_INTERSIL n
        WLAN_VENDOR_MARVELL n
        WLAN_VENDOR_MEDIATEK n
        WLAN_VENDOR_MICROCHIP n
        WLAN_VENDOR_RALINK n
        WLAN_VENDOR_REALTEK n
        WLAN_VENDOR_RSI n
        WLAN_VENDOR_ST n
        WLAN_VENDOR_TI n
        WLAN_VENDOR_ZYDAS n
        WLAN_VENDOR_QUANTENNA n
        FUJITSU_ES n
        MEDIA_ANALOG_TV_SUPPORT n
        MEDIA_DIGITAL_TV_SUPPORT n
        DRM_RADEON n
        DRM_AMDGPU n
        DRM_NOUVEAU n
        DRM_AST n
        DRM_MGAG200 n
        DRM_ETNAVIV n
        DRM_VGEM n
        DRM_VKMS n
        DRM_GMA500 n
        DRM_UDL n
        DRM_AST n
        DRM_MGAG200 n
        DRM_QXL n
        DRM_BOCHS n
        DRM_I2C_CH7006 n
        DRM_I2C_SIL164 n
        DRM_I2C_NXP_TDA998X n
        DRM_I2C_NXP_TDA9950 n
        AMD_SFH_HID n
        MEMSTICK n
        INFINIBAND n
        GREYBUS n
        SURFACE_PLATFORMS n
        XILINX_VCU n
        IIO n
        IPACK_BUS n
        FPGA n
        UNISYS_VISORBUS n
        SIOX n
        REISERFS_FS n
        JFS_FS n
        GFS2_FS n
        OCFS2_FS n
        F2FS_FS n
        NILFS2_FS n
        ORANGEFS_FS n
        ADFS_FS n
        AFFS_FS n
        HFS_FS n
        HFSPLUS_FS n
        BEFS_FS n
        BFS_FS n
        EFS_FS n
        JFFS2_FS n
        UBIFS_FS n
        VXFS_FS n
        MINIX_FS n
        OMFS_FS n
        HPFS_FS n
        QNX4FS_FS n
        QNX6FS_FS n
        SYSV_FS n
        UFS_FS n
        CODA_FS n
        AFS_FS n
        BTRFS_FS n
        EDAC n
        GPIO_AMDPT n
        GPIO_DWAPB n
        GPIO_GENERIC_PLATFORM n
        GPIO_ICH n
        GPIO_MB86S7X n
        GPIO_VX855 n
        GPIO_XILINX n
        GPIO_AMD_FCH n
        GPIO_F7188X n
        GPIO_IT87 n
        GPIO_SCH n
        GPIO_SCH311X n
        GPIO_WINBOND n
        GPIO_WS16C48 n
        GPIO_ADP5588 n
        GPIO_MAX7300 n
        GPIO_MAX732X n
        GPIO_PCA953X n
        GPIO_PCA9570 n
        GPIO_PCF857X n
        GPIO_TPIC2810 n
        GPIO_AMD8111 n
        GPIO_BT8XX n
        GPIO_ML_IOH n
        GPIO_PCI_IDIO_16 n
        GPIO_PCIE_IDIO_24 n
        GPIO_RDC321X n
        GPIO_MAX3191X n
        GPIO_MAX7301 n
        GPIO_MC33880 n
        GPIO_PISOSR n
        GPIO_XRA1403 n
        GPIO_AGGREGATOR n
        GPIO_MOCKUP n
        ALTERA_MSGDMA n
        INTEL_IDXD n
        INTEL_IOATDMA n
        PLX_DMA n
        XILINX_ZYNQMP_DPDMA n
        QCOM_HIDMA_MGMT n
        QCOM_HIDMA n
        DW_EDMA n
        DW_EDMA_PCIE n
        SF_PDMA n
        DRM_CIRRUS_QEMU n
        DRM_GM12U320 n
        TINYDRM_HX8357D n
        TINYDRM_ILI9225 n
        TINYDRM_ILI9341 n
        TINYDRM_ILI9486 n
        TINYDRM_MI0283QT n
        TINYDRM_REPAPER n
        TINYDRM_ST7586 n
        TINYDRM_ST7735R n
        DRM_XEN n
        DRM_VBOXVIDEO n
        DRM_TDFX n
        DRM_R128 n
        DRM_MGA n
        DRM_SIS n
        DRM_VIA n
        DRM_SAVAGE n
        SENSORS_ABITUGURU n
        SENSORS_ABITUGURU3 n
        SENSORS_AD7314 n
        SENSORS_AD7414 n
        SENSORS_AD7418 n
        SENSORS_ADM1021 n
        SENSORS_ADM1025 n
        SENSORS_ADM1026 n
        SENSORS_ADM1029 n
        SENSORS_ADM1031 n
        SENSORS_ADM1177 n
        SENSORS_ADM9240 n
        SENSORS_ADT7310 n
        SENSORS_ADT7410 n
        SENSORS_ADT7411 n
        SENSORS_ADT7462 n
        SENSORS_ADT7470 n
        SENSORS_ADT7475 n
        SENSORS_AS370 n
        SENSORS_ASC7621 n
        SENSORS_AXI_FAN_CONTROL n
        SENSORS_K8TEMP n
        SENSORS_K10TEMP n
        SENSORS_FAM15H_POWER n
        SENSORS_AMD_ENERGY n
        SENSORS_APPLESMC n
        SENSORS_ASB100 n
        SENSORS_ASPEED n
        SENSORS_ATXP1 n
        SENSORS_DRIVETEMP n
        SENSORS_DS620 n
        SENSORS_DS1621 n
        SENSORS_I5K_AMB n
        SENSORS_F71805F n
        SENSORS_F71882FG n
        SENSORS_F75375S n
        SENSORS_FSCHMD n
        SENSORS_FTSTEUTATES n
        SENSORS_GL518SM n
        SENSORS_GL520SM n
        SENSORS_G760A n
        SENSORS_G762 n
        SENSORS_HIH6130 n
        SENSORS_I5500 n
        SENSORS_IT87 n
        SENSORS_JC42 n
        SENSORS_POWR1220 n
        SENSORS_LINEAGE n
        SENSORS_LTC2945 n
        SENSORS_LTC2947_I2C n
        SENSORS_LTC2947_SPI n
        SENSORS_LTC2990 n
        SENSORS_LTC2992 n
        SENSORS_LTC4151 n
        SENSORS_LTC4215 n
        SENSORS_LTC4222 n
        SENSORS_LTC4245 n
        SENSORS_LTC4260 n
        SENSORS_LTC4261 n
        SENSORS_MAX1111 n
        SENSORS_MAX127 n
        SENSORS_MAX16065 n
        SENSORS_MAX1619 n
        SENSORS_MAX1668 n
        SENSORS_MAX197 n
        SENSORS_MAX31722 n
        SENSORS_MAX31730 n
        SENSORS_MAX6621 n
        SENSORS_MAX6639 n
        SENSORS_MAX6642 n
        SENSORS_MAX6650 n
        SENSORS_MAX6697 n
        SENSORS_MAX31790 n
        SENSORS_MCP3021 n
        SENSORS_TC654 n
        SENSORS_MR75203 n
        SENSORS_ADCXX n
        SENSORS_LM63 n
        SENSORS_LM70 n
        SENSORS_LM73 n
        SENSORS_LM75 n
        SENSORS_LM77 n
        SENSORS_LM78 n
        SENSORS_LM80 n
        SENSORS_LM83 n
        SENSORS_LM85 n
        SENSORS_LM87 n
        SENSORS_LM90 n
        SENSORS_LM92 n
        SENSORS_LM93 n
        SENSORS_LM95234 n
        SENSORS_LM95241 n
        SENSORS_LM95245 n
        SENSORS_PC87360 n
        SENSORS_PC87427 n
        SENSORS_NTC_THERMISTOR n
        SENSORS_NCT6683 n
        SENSORS_NCT6775 n
        SENSORS_NCT7802 n
        SENSORS_NCT7904 n
        SENSORS_NPCM7XX n
        SENSORS_PCF8591 n
        PMBUS n
        SENSORS_SBTSI n
        SENSORS_SHT15 n
        SENSORS_SHT21 n
        SENSORS_SHT3x n
        SENSORS_SHTC1 n
        SENSORS_SIS5595 n
        SENSORS_DME1737 n
        SENSORS_EMC1403 n
        SENSORS_EMC2103 n
        SENSORS_EMC6W201 n
        SENSORS_SMSC47M1 n
        SENSORS_SMSC47M192 n
        SENSORS_SMSC47B397 n
        SENSORS_SCH5627 n
        SENSORS_SCH5636 n
        SENSORS_STTS751 n
        SENSORS_SMM665 n
        SENSORS_ADC128D818 n
        SENSORS_ADS7828 n
        SENSORS_ADS7871 n
        SENSORS_AMC6821 n
        SENSORS_INA209 n
        SENSORS_INA2XX n
        SENSORS_INA3221 n
        SENSORS_TC74 n
        SENSORS_THMC50 n
        SENSORS_TMP102 n
        SENSORS_TMP103 n
        SENSORS_TMP108 n
        SENSORS_TMP401 n
        SENSORS_TMP421 n
        SENSORS_TMP513 n
        SENSORS_VIA_CPUTEMP n
        SENSORS_VIA686A n
        SENSORS_VT1211 n
        SENSORS_VT8231 n
        SENSORS_W83773G n
        SENSORS_W83781D n
        SENSORS_W83791D n
        SENSORS_W83792D n
        SENSORS_W83793 n
        SENSORS_W83795 n
        SENSORS_W83L785TS n
        SENSORS_W83L786NG n
        SENSORS_W83627HF n
        SENSORS_W83627EHF n
        SENSORS_XGENE n
        I2C_CBUS_GPIO n
        I2C_DESIGNWARE_PLATFORM n
        I2C_DESIGNWARE_PCI n
        I2C_EMEV2 n
        I2C_GPIO n
        I2C_OCORES n
        I2C_PCA_PLATFORM n
        I2C_SIMTEC n
        I2C_XILINX n
        I2C_DIOLAN_U2C n
        I2C_PARPORT n
        I2C_ROBOTFUZZ_OSIF n
        I2C_TAOS_EVM n
        I2C_TINY_USB n
        I2C_MLXCPLD n
        SPI_ALTERA n
        SPI_AXI_SPI_ENGINE n
        SPI_BITBANG n
        SPI_BUTTERFLY n
        SPI_CADENCE n
        SPI_DESIGNWARE n
        SPI_NXP_FLEXSPI n
        SPI_GPIO n
        SPI_LM70_LLP n
        SPI_LANTIQ_SSC n
        SPI_OC_TINY n
        SPI_PXA2XX n
        SPI_ROCKCHIP n
        SPI_SC18IS602 n
        SPI_SIFIVE n
        SPI_MXIC n
        SPI_XCOMM n
        SPI_XILINX n
        SPI_ZYNQMP_GQSPI n
        SPI_AMD n
        INPUT_JOYSTICK n
        INPUT_TABLET n
        KEYBOARD_ADP5588 n
        KEYBOARD_ADP5589 n
        KEYBOARD_APPLESPI n
        KEYBOARD_QT1050 n
        KEYBOARD_QT1070 n
        KEYBOARD_QT2160 n
        KEYBOARD_DLINK_DIR685 n
        KEYBOARD_LKKBD n
        KEYBOARD_GPIO n
        KEYBOARD_GPIO_POLLED n
        KEYBOARD_TCA6416 n
        KEYBOARD_TCA8418 n
        KEYBOARD_MATRIX n
        KEYBOARD_LM8323 n
        KEYBOARD_LM8333 n
        KEYBOARD_MAX7359 n
        KEYBOARD_MCS n
        KEYBOARD_MPR121 n
        KEYBOARD_NEWTON n
        KEYBOARD_OPENCORES n
        KEYBOARD_SAMSUNG n
        KEYBOARD_STOWAWAY n
        KEYBOARD_SUNKBD n
        KEYBOARD_TM2_TOUCHKEY n
        KEYBOARD_XTKBD n
        INPUT_TOUCHSCREEN n
        VIDEO_HI556 n
        VIDEO_IMX214 n
        VIDEO_IMX219 n
        VIDEO_IMX258 n
        VIDEO_IMX274 n
        VIDEO_IMX290 n
        VIDEO_IMX319 n
        VIDEO_IMX355 n
        VIDEO_OV02A10 n
        VIDEO_OV2640 n
        VIDEO_OV2659 n
        VIDEO_OV2680 n
        VIDEO_OV2685 n
        VIDEO_OV2740 n
        VIDEO_OV5647 n
        VIDEO_OV6650 n
        VIDEO_OV5670 n
        VIDEO_OV5675 n
        VIDEO_OV5695 n
        VIDEO_OV7251 n
        VIDEO_OV772X n
        VIDEO_OV7640 n
        VIDEO_OV7670 n
        VIDEO_OV7740 n
        VIDEO_OV8856 n
        VIDEO_OV9640 n
        VIDEO_OV9650 n
        VIDEO_OV9734 n
        VIDEO_OV13858 n
        VIDEO_VS6624 n
        VIDEO_MT9M001 n
        VIDEO_MT9M032 n
        VIDEO_MT9M111 n
        VIDEO_MT9P031 n
        VIDEO_MT9T001 n
        VIDEO_MT9T112 n
        VIDEO_MT9V011 n
        VIDEO_MT9V032 n
        VIDEO_MT9V111 n
        VIDEO_SR030PC30 n
        VIDEO_NOON010PC30 n
        VIDEO_M5MOLS n
        VIDEO_RDACM20 n
        VIDEO_RJ54N1 n
        VIDEO_S5K6AA n
        VIDEO_S5K6A3 n
        VIDEO_S5K4ECGX n
        VIDEO_S5K5BAF n
        VIDEO_CCS n
        VIDEO_ET8EK8 n
        VIDEO_S5C73M3 n
        VIDEO_AD5820 n
        VIDEO_AK7375 n
        VIDEO_DW9714 n
        VIDEO_DW9768 n
        VIDEO_DW9807_VCM n
        VIDEO_ADP1653 n
        VIDEO_LM3560 n
        VIDEO_LM3646 n
        CXD2880_SPI_DRV n
        RC_CORE n
        USB_GSPCA n
        MFD_BCM590XX n
        MFD_BD9571MWV n
        MFD_AXP20X_I2C n
        MFD_DA9052_SPI n
        MFD_DA9062 n
        MFD_DA9063 n
        MFD_DA9150 n
        MFD_DLN2 n
        MFD_MC13XXX_SPI n
        MFD_MC13XXX_I2C n
        MFD_MP2629 n
        MFD_INTEL_QUARK_I2C_GPIO n
        INTEL_SOC_PMIC_BXTWC n
        INTEL_SOC_PMIC_CHTDC_TI n
        MFD_INTEL_PMT n
        MFD_IQS62X n
        MFD_JANZ_CMODIO n
        MFD_88PM800 n
        MFD_88PM805 n
        MFD_MAX14577 n
        MFD_MAX77693 n
        MFD_MAX8907 n
        MFD_MT6360 n
        MFD_MENF21BMC n
        EZX_PCAP n
        MFD_VIPERBOARD n
        MFD_RETU n
        MFD_PCF50633 n
        MFD_RDC321X n
        MFD_RT5033 n
        MFD_SI476X_CORE n
        MFD_SKY81452 n
        MFD_LP3943 n
        MFD_TI_LMU n
        TPS6105X n
        TPS65010 n
        TPS6507X n
        MFD_TPS65086 n
        MFD_TI_LP873X n
        MFD_TPS65912_I2C n
        MFD_TPS65912_SPI n
        MFD_WL1273_CORE n
        MFD_LM3533 n
        MFD_VX855 n
        MFD_ARIZONA_I2C n
        MFD_ARIZONA_SPI n
        MFD_WM831X_SPI n
        MFD_WM8994 n
        MFD_INTEL_M10_BMC n
        MTD n
        NET_DSA n
        NET_VENDOR_3COM n
        NET_VENDOR_ADAPTEC n
        NET_VENDOR_AGERE n
        NET_VENDOR_ALACRITECH n
        NET_VENDOR_ALTEON n
        NET_VENDOR_AMAZON n
        NET_VENDOR_AMD n
        NET_VENDOR_AQUANTIA n
        NET_VENDOR_ARC n
        NET_VENDOR_ATHEROS n
        NET_VENDOR_AURORA n
        NET_VENDOR_BROADCOM n
        NET_VENDOR_BROCADE n
        NET_VENDOR_CADENCE n
        NET_VENDOR_CAVIUM n
        NET_VENDOR_CHELSIO n
        NET_VENDOR_CISCO n
        NET_VENDOR_CORTINA n
        NET_VENDOR_DEC n
        NET_TULIP n
        NET_VENDOR_DLINK n
        NET_VENDOR_EMULEX n
        NET_VENDOR_EZCHIP n
        NET_VENDOR_GOOGLE n
        NET_VENDOR_HUAWEI n
        NET_VENDOR_I825XX n
        NET_VENDOR_MARVELL n
        NET_VENDOR_MELLANOX n
        NET_VENDOR_MICREL n
        NET_VENDOR_MICROCHIP n
        NET_VENDOR_MICROSEMI n
        NET_VENDOR_MYRI n
        NET_VENDOR_NATSEMI n
        NET_VENDOR_NETERION n
        NET_VENDOR_NETRONOME n
        NET_VENDOR_NI n
        NET_VENDOR_8390 n
        NET_VENDOR_NVIDIA n
        NET_VENDOR_OKI n
        NET_VENDOR_PACKET_ENGINES n
        NET_VENDOR_PENSANDO n
        NET_VENDOR_QLOGIC n
        NET_VENDOR_QUALCOMM n
        NET_VENDOR_RDC n
        NET_VENDOR_RENESAS n
        NET_VENDOR_ROCKER n
        NET_VENDOR_SAMSUNG n
        NET_VENDOR_SEEQ n
        NET_VENDOR_SOLARFLARE n
        NET_VENDOR_SILAN n
        NET_VENDOR_SIS n
        NET_VENDOR_SMSC n
        NET_VENDOR_SOCIONEXT n
        NET_VENDOR_STMICRO n
        NET_VENDOR_SUN n
        NET_VENDOR_SYNOPSYS n
        NET_VENDOR_TEHUTI n
        NET_VENDOR_TI n
        NET_VENDOR_VIA n
        NET_VENDOR_WIZNET n
        NET_VENDOR_XILINX n
        HIPPI n
        USE_MDIO n
        PPP m
        SLIP n
        WAN n
        LIBNVDIMM n
        ALIENWARE_WMI n
        HUAWEI_WMI n
        MXM_WMI n
        PEAQ_WMI n
        XIAOMI_WMI n
        ACERHDF n
        ACER_WIRELESS n
        ACER_WMI n
        AMD_PMC n
        APPLE_GMUX n
        ASUS_LAPTOP n
        ASUS_WIRELESS n
        ASUS_WMI n
        EEEPC_LAPTOP n
        AMILO_RFKILL n
        FUJITSU_LAPTOP n
        FUJITSU_TABLET n
        GPD_POCKET_FAN n
        HP_ACCEL n
        HP_WIRELESS n
        HP_WMI n
        IBM_RTL n
        IDEAPAD_LAPTOP n
        THINKPAD_ACPI n
        MSI_LAPTOP n
        MSI_WMI n
        PCENGINES_APU2 n
        SAMSUNG_LAPTOP n
        SAMSUNG_Q10 n
        TOSHIBA_BT_RFKILL n
        TOSHIBA_HAPS n
        TOSHIBA_WMI n
        ACPI_CMPC n
        COMPAL_LAPTOP n
        LG_LAPTOP n
        PANASONIC_LAPTOP n
        SONY_LAPTOP n
        SYSTEM76_ACPI n
        TOPSTAR_LAPTOP n
        MLX_PLATFORM n
        PDA_POWER n
        TEST_POWER n
        CHARGER_ADP5061 n
        BATTERY_CW2015 n
        BATTERY_DS2780 n
        BATTERY_DS2781 n
        BATTERY_DS2782 n
        BATTERY_SBS n
        CHARGER_SBS n
        MANAGER_SBS n
        BATTERY_BQ27XXX n
        BATTERY_MAX17040 n
        BATTERY_MAX17042 n
        CHARGER_MAX8903 n
        CHARGER_LP8727 n
        CHARGER_GPIO n
        CHARGER_MANAGER n
        CHARGER_LT3651 n
        CHARGER_BQ2415X n
        CHARGER_BQ24190 n
        CHARGER_BQ24257 n
        CHARGER_BQ24735 n
        CHARGER_BQ2515X n
        CHARGER_BQ25890 n
        CHARGER_BQ25980 n
        CHARGER_SMB347 n
        BATTERY_GAUGE_LTC2941 n
        CHARGER_RT9455 n
        CHARGER_BD99954 n
        PPS n
        PTP_1588_CLOCK n
        REGULATOR_88PG86X n
        REGULATOR_ACT8865 n
        REGULATOR_AD5398 n
        REGULATOR_DA9210 n
        REGULATOR_DA9211 n
        REGULATOR_FAN53555 n
        REGULATOR_GPIO n
        REGULATOR_ISL9305 n
        REGULATOR_ISL6271A n
        REGULATOR_LP3971 n
        REGULATOR_LP3972 n
        REGULATOR_LP872X n
        REGULATOR_LP8755 n
        REGULATOR_LTC3589 n
        REGULATOR_LTC3676 n
        REGULATOR_MAX1586 n
        REGULATOR_MAX8649 n
        REGULATOR_MAX8660 n
        REGULATOR_MAX8952 n
        REGULATOR_MAX77826 n
        REGULATOR_MP8859 n
        REGULATOR_MT6311 n
        REGULATOR_PCA9450 n
        REGULATOR_PV88060 n
        REGULATOR_PV88080 n
        REGULATOR_PV88090 n
        REGULATOR_RASPBERRYPI_TOUCHSCREEN_ATTINY n
        REGULATOR_RT4801 n
        REGULATOR_RTMV20 n
        REGULATOR_SLG51000 n
        REGULATOR_TPS51632 n
        REGULATOR_TPS62360 n
        REGULATOR_TPS65023 n
        REGULATOR_TPS6507X n
        REGULATOR_TPS65132 n
        REGULATOR_TPS6524X n
        RTC_DRV_ABB5ZES3 n
        RTC_DRV_ABEOZ9 n
        RTC_DRV_ABX80X n
        RTC_DRV_DS1307 n
        RTC_DRV_DS1374 n
        RTC_DRV_DS1672 n
        RTC_DRV_MAX6900 n
        RTC_DRV_RS5C372 n
        RTC_DRV_ISL1208 n
        RTC_DRV_ISL12022 n
        RTC_DRV_X1205 n
        RTC_DRV_PCF8523 n
        RTC_DRV_PCF85063 n
        RTC_DRV_PCF85363 n
        RTC_DRV_PCF8563 n
        RTC_DRV_PCF8583 n
        RTC_DRV_M41T80 n
        RTC_DRV_BQ32K n
        RTC_DRV_S35390A n
        RTC_DRV_FM3130 n
        RTC_DRV_RX8010 n
        RTC_DRV_RX8581 n
        RTC_DRV_RX8025 n
        RTC_DRV_EM3027 n
        RTC_DRV_RV3028 n
        RTC_DRV_RV3032 n
        RTC_DRV_RV8803 n
        RTC_DRV_SD3078 n
        RTC_DRV_M41T93 n
        RTC_DRV_M41T94 n
        RTC_DRV_DS1302 n
        RTC_DRV_DS1305 n
        RTC_DRV_DS1343 n
        RTC_DRV_DS1347 n
        RTC_DRV_DS1390 n
        RTC_DRV_MAX6916 n
        RTC_DRV_R9701 n
        RTC_DRV_RX4581 n
        RTC_DRV_RS5C348 n
        RTC_DRV_MAX6902 n
        RTC_DRV_PCF2123 n
        RTC_DRV_MCP795 n
        RTC_DRV_DS3232 n
        RTC_DRV_PCF2127 n
        RTC_DRV_RV3029C2 n
        RTC_DRV_RX6110 n
        RTC_DRV_DS1286 n
        RTC_DRV_DS1511 n
        RTC_DRV_DS1553 n
        RTC_DRV_DS1685_FAMILY n
        RTC_DRV_DS1742 n
        RTC_DRV_DS2404 n
        RTC_DRV_STK17TA8 n
        RTC_DRV_M48T86 n
        RTC_DRV_M48T35 n
        RTC_DRV_M48T59 n
        RTC_DRV_MSM6242 n
        RTC_DRV_BQ4802 n
        RTC_DRV_RP5C01 n
        RTC_DRV_V3020 n
        COMEDI n
        SPI n
        FB_TFT n
        MOST n
        RTL8192E n
        WIMAX n
        TARGET_CORE n
        ISCSI_TARGET n
        SERIAL_MAX3100 n
        SERIAL_MAX310X n
        SERIAL_UARTLITE n
        SERIAL_JSM n
        SERIAL_LANTIQ n
        SERIAL_SCCNXP n
        SERIAL_SC16IS7XX n
        SERIAL_BCM63XX n
        SERIAL_ALTERA_JTAGUART n
        SERIAL_ALTERA_UART n
        SERIAL_IFX6X60 n
        SERIAL_ARC n
        SERIAL_RP2 n
        SERIAL_FSL_LPUART n
        SERIAL_FSL_LINFLEXUART n
        SERIAL_SPRD n
        USB_CHIPIDEA n
        FB_CIRRUS n
        FB_PM2 n
        FB_CYBER2000 n
        FB_ARC n
        FB_ASILIANT n
        FB_IMSTT n
        FB_VGA16 n
        FB_UVESA n
        FB_N411 n
        FB_HGA n
        FB_OPENCORES n
        FB_S1D13XXX n
        FB_NVIDIA n
        FB_RIVA n
        FB_I740 n
        FB_LE80578 n
        FB_MATROX n
        FB_RADEON n
        FB_ATY128 n
        FB_ATY n
        FB_S3 n
        FB_SAVAGE n
        FB_SIS n
        FB_VIA n
        FB_NEOMAGIC n
        FB_KYRO n
        FB_3DFX n
        FB_VOODOO1 n
        FB_VT8623 n
        FB_TRIDENT n
        FB_ARK n
        FB_PM3 n
        FB_CARMINE n
        FB_SMSCUFX n
        FB_UDL n
        FB_IBM_GXT4500 n
        FB_VIRTUAL n
        XEN_FBDEV_FRONTEND n
        FB_METRONOME n
        FB_MB862XX n
        FB_SIMPLE n
        FB_SM712 n
        BACKLIGHT_KTD253 n
        BACKLIGHT_APPLE n
        BACKLIGHT_QCOM_WLED n
        BACKLIGHT_SAHARA n
        BACKLIGHT_ADP8860 n
        BACKLIGHT_ADP8870 n
        BACKLIGHT_LM3639 n
        BACKLIGHT_GPIO n
        BACKLIGHT_LV5207LP n
        BACKLIGHT_BD6107 n
        BACKLIGHT_ARCXCNN n
        W1 n
        WDAT_WDT n
        XILINX_WATCHDOG n
        ZIIRAVE_WATCHDOG n
        CADENCE_WATCHDOG n
        DW_WATCHDOG n
        MAX63XX_WATCHDOG n
        ACQUIRE_WDT n
        ADVANTECH_WDT n
        ALIM1535_WDT n
        ALIM7101_WDT n
        EBC_C384_WDT n
        F71808E_WDT n
        SP5100_TCO n
        SBC_FITPC2_WATCHDOG n
        EUROTECH_WDT n
        IB700_WDT n
        IBMASR n
        WAFER_WDT n
        I6300ESB_WDT n
        IE6XX_WDT n
        ITCO_VENDOR_SUPPORT n
        IT8712F_WDT n
        IT87_WDT n
        HP_WATCHDOG n
        SC1200_WDT n
        PC87413_WDT n
        NV_TCO n
        60XX_WDT n
        CPU5_WDT n
        SMSC_SCH311X_WDT n
        SMSC37B787_WDT n
        TQMX86_WDT n
        VIA_WDT n
        W83627HF_WDT n
        W83877F_WDT n
        W83977F_WDT n
        MACHZ_WDT n
        SBC_EPX_C3_WATCHDOG n
        NI903X_WDT n
        NIC7018_WDT n
        MEN_A21_WDT n
        XEN_WDT n
        PCIPCWATCHDOG n
        WDTPCI n
        SND_PCSP n
        SND_MTPAV n
        SND_MTS64 n
        SND_SERIAL_U16550 n
        SND_MPU401 n
        SND_PORTMAN2X4 n
        SND_AD1889 n
        SND_ALS300 n
        SND_ALS4000 n
        SND_ALI5451 n
        SND_ASIHPI n
        SND_ATIIXP n
        SND_ATIIXP_MODEM n
        SND_AU8810 n
        SND_AU8820 n
        SND_AU8830 n
        SND_AW2 n
        SND_AZT3328 n
        SND_BT87X n
        SND_CA0106 n
        SND_CMIPCI n
        SND_OXYGEN n
        SND_CS4281 n
        SND_CS46XX n
        SND_CTXFI n
        SND_DARLA20 n
        SND_GINA20 n
        SND_LAYLA20 n
        SND_DARLA24 n
        SND_GINA24 n
        SND_LAYLA24 n
        SND_MONA n
        SND_MIA n
        SND_ECHO3G n
        SND_INDIGO n
        SND_INDIGOIO n
        SND_INDIGODJ n
        SND_INDIGOIOX n
        SND_INDIGODJX n
        SND_EMU10K1 n
        SND_EMU10K1X n
        SND_ENS1370 n
        SND_ENS1371 n
        SND_ES1938 n
        SND_ES1968 n
        SND_FM801 n
        SND_HDSP n
        SND_HDSPM n
        SND_ICE1712 n
        SND_ICE1724 n
        SND_INTEL8X0 n
        SND_INTEL8X0M n
        SND_KORG1212 n
        SND_LOLA n
        SND_LX6464ES n
        SND_MAESTRO3 n
        SND_MIXART n
        SND_NM256 n
        SND_PCXHR n
        SND_RIPTIDE n
        SND_RME32 n
        SND_RME96 n
        SND_RME9652 n
        SND_SE6X n
        SND_SONICVIBES n
        SND_TRIDENT n
        SND_VIA82XX n
        SND_VIA82XX_MODEM n
        SND_VIRTUOSO n
        SND_VX222 n
        SND_YMFPCI n
        SND_SOC n
        AMD_PHY n
        ADIN_PHY n
        AQUANTIA_PHY n
        AX88796B_PHY n
        BROADCOM_PHY n
        BCM54140_PHY n
        BCM84881_PHY n
        BCM87XX_PHY n
        CICADA_PHY n
        CORTINA_PHY n
        DAVICOM_PHY n
        ICPLUS_PHY n
        LXT_PHY n
        INTEL_XWAY_PHY n
        LSI_ET1011C_PHY n
        MARVELL_PHY n
        MARVELL_10G_PHY n
        MICREL_PHY n
        MICROCHIP_T1_PHY n
        MICROSEMI_PHY n
        NATIONAL_PHY n
        NXP_TJA11XX_PHY n
        AT803X_PHY n
        QSEMI_PHY n
        RENESAS_PHY n
        ROCKCHIP_PHY n
        STE10XP n
        TERANETICS_PHY n
        DP83822_PHY n
        DP83TC811_PHY n
        DP83848_PHY n
        DP83867_PHY n
        DP83869_PHY n
        XILINX_GMII2RGMII n
        ACPI_NFIT n
        AMD_IOMMU n
        XEN n
        XEN_BACKEND n
        MFD_MADERA n
        MAC n
        EISA n
        ISCSI_TCP n
        SCSI_CXGB3_ISCSI n
        SCSI_CXGB4_ISCSI n
        SCSI_BNX2_ISCSI n
        BE2ISCSI n
        SCSI_HPSA n
        SCSI_3W_SAS n
        SCSI_ACARD n
        SCSI_AACRAID n
        SCSI_AIC94XX n
        SCSI_MVSAS n
        SCSI_MVUMI n
        SCSI_DPT_I2O n
        SCSI_ADVANSYS n
        SCSI_ESAS2R n
        MEGARAID_NEWGEN n
        MEGARAID_LEGACY n
        MEGARAID_SAS n
        SCSI_MPT3SAS n
        SCSI_MPT2SAS n
        SCSI_SMARTPQI n
        SCSI_UFS_DWC_TC_PCI n
        SCSI_UFS_DWC_TC_PLATFORM n
        SCSI_HPTIOP n
        SCSI_BUSLOGIC n
        SCSI_MYRB n
        SCSI_MYRS n
        VMWARE_PVSCSI n
        XEN_SCSI_FRONTEND n
        LIBFC n
        SCSI_SNIC n
        SCSI_DMX3191D n
        SCSI_FDOMAIN_PCI n
        SCSI_GDTH n
        SCSI_ISCI n
        SCSI_IPS n
        SCSI_INITIO n
        SCSI_INIA100 n
        SCSI_PPA n
        SCSI_IMM n
        SCSI_STEX n
        SCSI_SYM53C8XX_2 n
        SCSI_IPR n
        SCSI_QLOGIC_1280 n
        SCSI_QLA_FC n
        SCSI_QLA_ISCSI n
        QEDI n
        SCSI_LPFC n
        SCSI_DC395x n
        SCSI_AM53C974 n
        SCSI_WD719X n
        SCSI_PMCRAID n
        SCSI_PM8001 n
        SCSI_BFA_FC n
        SCSI_CHELSIO_FCOE n
        PATA_ATP867X n
        PATA_CMD64X n
        PATA_CYPRESS n
        PATA_NINJA32 n
        PATA_NS87415 n
        PATA_OPTIDMA n
        PATA_PDC_OLD n
        PATA_RADISYS n
        PATA_RDC n
        PATA_SCH n
        PATA_TOSHIBA n
        PATA_CMD640_PCI n
        PATA_OPTI n
        PATA_ACPI n
        RTL8723BS n
        R8712U n
        R8188EU n
        VT6656 n
        RTS5208 n
        LTE_GDM724X n
        NITRO_ENCLAVES n
        8139CP n
        8139TOO n
        8139TOO_8129 n
        8139TOO_PIO n
        8139TOO_TUNE_TWISTER n
        8139_OLD_RX_RESET n
        ACER_WMI n
        ADIN_PHY n
        ALIENWARE_WMI n
        AMD_PHY n
        AQUANTIA_PHY n
        ASUS_WMI n
        ASYNC_MEMCPY n
        ASYNC_PQ n
        ASYNC_RAID6_RECOV n
        AT803X_PHY n
        ATA_BMDMA n
        ATA_GENERIC n
        ATA_PIIX n
        AX88796B_PHY n
        BACKLIGHT_RAVE_SP n
        BCM54140_PHY n
        BCM7XXX_PHY n
        BCM84881_PHY n
        BCM87XX_PHY n
        BCMA_DEBUG n
        BCMA_DRIVER_GMAC_CMN n
        BCMA_DRIVER_GPIO n
        BCMA_DRIVER_PCI n
        BCMA_HOST_PCI n
        BCMA_HOST_PCI_POSSIBLE n
        BCMA_HOST_SOC n
        BCM_NET_PHYLIB n
        BCM_VK_TTY n
        BROADCOM_PHY n
        BT_HCIBLUECARD n
        BT_HCIBT3C n
        BT_HCIDTL1 n
        CARDBUS n
        CARDMAN_4000 n
        CARDMAN_4040 n
        CDROM n
        CEPH_FSCACHE n
        CEPH_FS_POSIX_ACL n
        CEPH_FS_SECURITY_LABEL n
        CFG80211_WEXT_EXPORT n
        CICADA_PHY n
        CORTINA_PHY n
        DAVICOM_PHY n
        DELL_SMBIOS_WMI n
        DELL_WMI n
        DELL_WMI_AIO n
        DELL_WMI_DESCRIPTOR n
        DELL_WMI_LED n
        DELL_WMI_SYSMAN n
        DIMLIB n
        DP83822_PHY n
        DP83848_PHY n
        DP83867_PHY n
        DP83869_PHY n
        DP83TC811_PHY n
        DRM_TTM n
        DRM_VMWGFX_FBCON n
        EXTCON_INTEL_MRFLD n
        FB_HYPERV n
        FB_SM501 n
        FIXED_PHY n
        FUSION_CTL n
        FUSION_FC n
        FUSION_LAN n
        FUSION_LOGGING n
        FUSION_SAS n
        FUSION_SPI n
        GIGABYTE_WMI n
        GPIO_GENERIC n
        GPIO_KEMPLD n
        GPIO_MENZ127 n
        GPIO_TQMX86 n
        HID_HYPERV_MOUSE n
        HP_WMI n
        HSI_BOARDINFO n
        HSI_CHAR n
        HUAWEI_WMI n
        HYPERV_BALLOON n
        HYPERV_IOMMU n
        HYPERV_KEYBOARD n
        HYPERV_NET n
        HYPERV_STORAGE n
        HYPERV_TESTING n
        HYPERV_TIMER n
        HYPERV_UTILS n
        HYPERV_VSOCKETS n
        I2C_KEMPLD n
        I82092 n
        ICPLUS_PHY n
        IGB_HWMON n
        INPUT_ATC260X_ONKEY n
        INPUT_RAVE_SP_PWRBUTTON n
        INTEL_MRFLD_PWRBTN n
        INTEL_SOC_PMIC_BXTWC n
        INTEL_TELEMETRY n
        INTEL_WMI_SBL_FW_UPDATE n
        INTEL_WMI_THUNDERBOLT n
        INTEL_XWAY_PHY n
        IPW2100_DEBUG n
        IPW2100_MONITOR n
        IPW2200_DEBUG n
        IPW2200_MONITOR n
        IPW2200_PROMISCUOUS n
        IPW2200_QOS n
        IPW2200_RADIOTAP n
        IPWIRELESS n
        IWLEGACY n
        IWLEGACY_DEBUG n
        IXGBEVF_IPSEC n
        IXGBE_HWMON n
        IXGBE_IPSEC n
        KEMPLD_WDT n
        KEYBOARD_MTK_PMIC n
        LEDS_MT6323 n
        LED_TRIGGER_PHY n
        LG_LAPTOP n
        LIB80211 n
        LIB80211_CRYPT_CCMP n
        LIB80211_CRYPT_TKIP n
        LIB80211_CRYPT_WEP n
        LIB80211_DEBUG n
        LIBIPW n
        LIBIPW_DEBUG n
        LSI_ET1011C_PHY n
        LXT_PHY n
        MAC_EMUMOUSEBTN n
        MAPPING_DIRTY_HELPERS n
        MARVELL_10G_PHY n
        MARVELL_88X2222_PHY n
        MARVELL_PHY n
        MCB_LPC n
        MCB_PCI n
        MDIO n
        MDIO_BCM_UNIMAC n
        MDIO_BITBANG n
        MDIO_BUS n
        MDIO_CAVIUM n
        MDIO_DEVRES n
        MDIO_GPIO n
        MDIO_MSCC_MIIM n
        MDIO_MVUSB n
        MDIO_THUNDER n
        MD_CLUSTER n
        MD_FAULTY n
        MD_LINEAR n
        MD_MULTIPATH n
        MD_RAID0 n
        MD_RAID1 n
        MD_RAID10 n
        MD_RAID456 n
        MENZ069_WATCHDOG n
        MFD_ATC260X n
        MFD_SM501_GPIO n
        MFD_WCD934X n
        MICREL_PHY n
        MICROCHIP_PHY n
        MICROCHIP_T1_PHY n
        MICROSEMI_PHY n
        MICROSOFT_MANA n
        MII n
        MMC_ALCOR n
        MMC_REALTEK_USB n
        MMC_SDRICOH_CS n
        MSI_WMI n
        MUSB_PIO_ONLY n
        MXM_WMI n
        NATIONAL_PHY n
        NET_SELFTESTS n
        NET_VENDOR_FUJITSU n
        NET_VENDOR_XIRCOM n
        NVME_CORE n
        NVME_FABRICS n
        NVME_HWMON n
        NVME_MULTIPATH n
        NVME_TARGET_FC n
        NVME_TARGET_FCLOOP n
        NVME_TARGET_LOOP n
        NVME_TARGET_PASSTHRU n
        NVME_TARGET_TCP n
        NXP_C45_TJA11XX_PHY n
        NXP_TJA11XX_PHY n
        PATA_ACPI n
        PATA_ALI n
        PATA_AMD n
        PATA_ARTOP n
        PATA_ATIIXP n
        PATA_ATP867X n
        PATA_CMD640_PCI n
        PATA_CMD64X n
        PATA_CYPRESS n
        PATA_EFAR n
        PATA_HPT366 n
        PATA_HPT37X n
        PATA_HPT3X2N n
        PATA_HPT3X3 n
        PATA_HPT3X3_DMA n
        PATA_IT8213 n
        PATA_IT821X n
        PATA_JMICRON n
        PATA_LEGACY n
        PATA_MARVELL n
        PATA_MPIIX n
        PATA_NETCELL n
        PATA_NINJA32 n
        PATA_NS87410 n
        PATA_NS87415 n
        PATA_OLDPIIX n
        PATA_OPTI n
        PATA_OPTIDMA n
        PATA_PCMCIA n
        PATA_PDC2027X n
        PATA_PDC_OLD n
        PATA_RADISYS n
        PATA_RDC n
        PATA_RZ1000 n
        PATA_SCH n
        PATA_SERVERWORKS n
        PATA_SIL680 n
        PATA_SIS n
        PATA_TOSHIBA n
        PATA_TRIFLEX n
        PATA_VIA n
        PATA_WINBOND n
        PCCARD_NONSTATIC n
        PCI_HYPERV n
        PCI_HYPERV_INTERFACE n
        PCMCIA n
        PCMCIA_AHA152X n
        PCMCIA_FDOMAIN n
        PCMCIA_FMVJ18X n
        PCMCIA_LOAD_CIS n
        PCMCIA_QLOGIC n
        PCMCIA_RAYCS n
        PCMCIA_SYM53C500 n
        PCMCIA_WL3501 n
        PCMCIA_XIRC2PS n
        PCS_XPCS n
        PD6729 n
        PDC_ADMA n
        PEAQ_WMI n
        PHY_SAMSUNG_USB2 n
        PINCTRL_MCP23S08_I2C n
        PLDMFW n
        QSEMI_PHY n
        R8169 n
        RAVE_SP_EEPROM n
        RAVE_SP_WATCHDOG n
        REALTEK_PHY n
        REGMAP_SLIMBUS n
        REGMAP_SPMI n
        REGULATOR_ATC260X n
        REGULATOR_MT6323 n
        REGULATOR_MT6358 n
        REGULATOR_MT6397 n
        RENESAS_PHY n
        ROCKCHIP_PHY n
        RTC_DRV_MT6397 n
        RTL8192E n
        RTLLIB_CRYPTO_CCMP n
        RTLLIB_CRYPTO_TKIP n
        RTLLIB_CRYPTO_WEP n
        SATA_DWC n
        SATA_DWC_DEBUG n
        SATA_DWC_OLD_DMA n
        SATA_MV n
        SATA_NV n
        SATA_PROMISE n
        SATA_QSTOR n
        SATA_SIL n
        SATA_SIS n
        SATA_SVW n
        SATA_SX4 n
        SATA_ULI n
        SATA_VIA n
        SATA_VITESSE n
        SCR24X n
        SCSI_ENCLOSURE n
        SCSI_FDOMAIN n
        SCSI_LOWLEVEL_PCMCIA n
        SENSORS_LIS3LV02D n
        SERIAL_8250_CS n
        SERIAL_8250_MEN_MCB n
        SERIAL_MEN_Z135 n
        SLIM_QCOM_CTRL n
        SMSC_PHY n
        SND_BEBOB n
        SND_DICE n
        SND_FIREFACE n
        SND_FIREWIRE_DIGI00X n
        SND_FIREWIRE_LIB n
        SND_FIREWIRE_MOTU n
        SND_FIREWIRE_TASCAM n
        SND_FIREWORKS n
        SND_ISIGHT n
        SND_OXFW n
        SND_PCMCIA n
        SND_PDAUDIOCF n
        SND_VXPOCKET n
        SND_VX_LIB n
        SSB_DRIVER_GPIO n
        SSB_DRIVER_PCICORE n
        SSB_DRIVER_PCICORE_POSSIBLE n
        SSB_PCIHOST n
        SSB_PCIHOST_POSSIBLE n
        SSB_PCMCIAHOST n
        SSB_PCMCIAHOST_POSSIBLE n
        SSB_SDIOHOST n
        SSB_SDIOHOST_POSSIBLE n
        SSB_SPROM n
        STE10XP n
        SUNRPC_DISABLE_INSECURE_ENCTYPES n
        SWPHY n
        SYNCLINK_CS n
        TERANETICS_PHY n
        TOSHIBA_WMI n
        UIO_HV_GENERIC n
        USB4_DEBUGFS_WRITE n
        USB4_DMA_TEST n
        USB4_NET n
        USB_CATC n
        USB_CDNS3 n
        USB_CDNS3_GADGET n
        USB_CDNS3_HOST n
        USB_CDNS3_PCI_WRAP n
        USB_CDNSP_GADGET n
        USB_CDNSP_HOST n
        USB_CDNSP_PCI n
        USB_DWC2_DEBUG n
        USB_DWC2_DUAL_ROLE n
        USB_DWC2_HOST n
        USB_DWC2_PCI n
        USB_DWC2_PERIPHERAL n
        USB_DWC2_TRACK_MISSED_SOFS n
        USB_DWC3_DUAL_ROLE n
        USB_DWC3_GADGET n
        USB_DWC3_HAPS n
        USB_DWC3_HOST n
        USB_DWC3_PCI n
        USB_DWC3_ULPI n
        USB_HCD_BCMA n
        USB_HCD_SSB n
        USB_HSO n
        USB_IPHETH n
        USB_ISP1760_DUAL_ROLE n
        USB_ISP1760_GADGET_ROLE n
        USB_ISP1760_HCD n
        USB_ISP1760_HOST_ROLE n
        USB_KAWETH n
        USB_LAN78XX n
        USB_MUSB_DUAL_ROLE n
        USB_MUSB_GADGET n
        USB_MUSB_HOST n
        USB_NET_AQC111 n
        USB_NET_AX88179_178A n
        USB_NET_AX8817X n
        USB_NET_CDCETHER n
        USB_NET_CDC_EEM n
        USB_NET_CDC_MBIM n
        USB_NET_CDC_NCM n
        USB_NET_CDC_SUBSET n
        USB_NET_CH9200 n
        USB_NET_CX82310_ETH n
        USB_NET_DM9601 n
        USB_NET_GL620A n
        USB_NET_HUAWEI_CDC_NCM n
        USB_NET_INT51X1 n
        USB_NET_KALMIA n
        USB_NET_MCS7830 n
        USB_NET_NET1080 n
        USB_NET_PLUSB n
        USB_NET_QMI_WWAN n
        USB_NET_RNDIS_HOST n
        USB_NET_SMSC75XX n
        USB_NET_SMSC95XX n
        USB_NET_SR9700 n
        USB_NET_SR9800 n
        USB_NET_ZAURUS n
        USB_OHCI_HCD_SSB n
        USB_PEGASUS n
        USB_RTL8150 n
        USB_RTL8152 n
        USB_RTL8153_ECM n
        USB_SIERRA_NET n
        USB_SL811_CS n
        USB_SL811_HCD_ISO n
        USB_USBNET n
        USB_VL600 n
        VIDEOBUF2_DMA_CONTIG n
        VITESSE_PHY n
        VMWARE_BALLOON n
        VMWARE_VMCI_VSOCKETS n
        WEXT_CORE n
        WEXT_PRIV n
        WEXT_PROC n
        WEXT_SPY n
        WIRELESS_EXT n
        WMI_BMOF n
        XIAOMI_WMI n
        XILINX_GMII2RGMII n
        YENTA n
        YENTA_ENE_TUNE n
        YENTA_O2 n
        YENTA_RICOH n
        YENTA_TI n
        YENTA_TOSHIBA n
        ACPI_WMI n
        ADV_SWBUTTON n
        ALTERA_MBOX n
        ALTERA_STAPL n
        ALTERA_TSE n
        APDS9802ALS n
        ATA_OVER_ETH n
        ATA_SFF n
        BATTERY_GOLDFISH n
        BATTERY_RT5033 n
        BCMA n
        BCM_KONA_USB2_PHY n
        BCM_VK n
        BLK_DEV_MD n
        BLK_DEV_NVME n
        BLK_DEV_PCIESSD_MTIP32XX n
        BLK_DEV_SR n
        BLK_DEV_SX8 n
        CEPH_FS n
        CFG80211_WEXT n
        CHARGER_BQ256XX n
        CHARGER_ISP1704 n
        CHARGER_LTC4162L n
        CHR_DEV_SCH n
        CHR_DEV_SG n
        CHR_DEV_ST n
        CX_ECAT n
        DM_RAID n
        DNET n
        DRM_GUD n
        DRM_VMWGFX n
        DS1682 n
        DW_XDATA_PCIE n
        E100 n
        E1000 n
        ENCLOSURE_SERVICES n
        ETHOC n
        FB_SM750 n
        FEALNX n
        FIELDBUS_DEV n
        FIREWIRE_SERIAL n
        FM10K n
        FUSION n
        GENWQE n
        GS_FPGABOOT n
        HDMI_LPE_AUDIO n
        HMC6352 n
        HSI n
        HTC_PASIC3 n
        HYPERV n
        I40E n
        ICE n
        ICS932S401 n
        IGB n
        IGBVF n
        IGC n
        INTEL_ATOMISP2_LED n
        INTEL_ATOMISP2_PM n
        INTEL_MENLOW n
        INTEL_OAKTRAIL n
        INTEL_SOC_PMIC_MRFLD n
        IPW2100 n
        IPW2200 n
        ISL29003 n
        ISL29020 n
        IWL3945 n
        IWL4965 n
        IXGB n
        IXGBE n
        IXGBEVF n
        JME n
        KS7010 n
        MAC80211_HWSIM n
        MACINTOSH_DRIVERS n
        MCB n
        MDIO_DEVICE n
        MFD_ATC260X_I2C n
        MFD_INTEL_PMC_BXT n
        MFD_KEMPLD n
        MFD_MT6397 n
        MFD_SM501 n
        MFD_TI_AM335X_TSCADC n
        MFD_TQMX86 n
        MHI_WWAN_CTRL n
        MISC_ALCOR_PCI n
        MISC_RTSX_USB n
        MMC_CB710 n
        MMC_MTK n
        MMC_SDHCI_F_SDH30 n
        MMC_SDHCI_XENON n
        MMC_TIFM_SD n
        MMC_TOSHIBA_PCI n
        MMC_USDHI6ROL0 n
        MMC_USHC n
        MMC_VIA_SDMMC n
        MMC_VUB300 n
        MMC_WBSD n
        NET_FC n
        NET_VENDOR_MICROSOFT n
        NET_VENDOR_REALTEK n
        NLS_CODEPAGE_1250 n
        NLS_CODEPAGE_1251 n
        NLS_CODEPAGE_737 n
        NLS_CODEPAGE_775 n
        NLS_CODEPAGE_852 n
        NLS_CODEPAGE_855 n
        NLS_CODEPAGE_857 n
        NLS_CODEPAGE_860 n
        NLS_CODEPAGE_861 n
        NLS_CODEPAGE_862 n
        NLS_CODEPAGE_863 n
        NLS_CODEPAGE_864 n
        NLS_CODEPAGE_865 n
        NLS_CODEPAGE_866 n
        NLS_CODEPAGE_869 n
        NLS_CODEPAGE_874 n
        NLS_CODEPAGE_932 n
        NLS_CODEPAGE_936 n
        NLS_CODEPAGE_949 n
        NLS_CODEPAGE_950 n
        NLS_ISO8859_13 n
        NLS_ISO8859_14 n
        NLS_ISO8859_2 n
        NLS_ISO8859_3 n
        NLS_ISO8859_4 n
        NLS_ISO8859_5 n
        NLS_ISO8859_6 n
        NLS_ISO8859_7 n
        NLS_ISO8859_8 n
        NLS_ISO8859_9 n
        NLS_KOI8_R n
        NLS_KOI8_U n
        NLS_MAC_CELTIC n
        NLS_MAC_CROATIAN n
        NLS_MAC_CYRILLIC n
        NLS_MAC_GAELIC n
        NLS_MAC_GREEK n
        NLS_MAC_ICELAND n
        NLS_MAC_INUIT n
        NLS_MAC_ROMANIAN n
        NLS_MAC_TURKISH n
        NVME_FC n
        NVME_TARGET n
        NVME_TCP n
        PCCARD n
        PHYLIB n
        PHY_PXA_28NM_HSIC n
        PHY_PXA_28NM_USB2 n
        PHY_QCOM_USB_HS n
        PHY_QCOM_USB_HSIC n
        PHY_TUSB1210 n
        PINCTRL_ALDERLAKE n
        PINCTRL_AMD n
        PINCTRL_BAYTRAIL n
        PINCTRL_BROXTON n
        PINCTRL_CANNONLAKE n
        PINCTRL_CEDARFORK n
        PINCTRL_CHERRYVIEW n
        PINCTRL_DENVERTON n
        PINCTRL_ELKHARTLAKE n
        PINCTRL_EMMITSBURG n
        PINCTRL_GEMINILAKE n
        PINCTRL_ICELAKE n
        PINCTRL_JASPERLAKE n
        PINCTRL_LAKEFIELD n
        PINCTRL_LEWISBURG n
        PINCTRL_LYNXPOINT n
        PINCTRL_MCP23S08 n
        PINCTRL_TIGERLAKE n
        PPPOE n
        PPPOL2TP n
        PPP_ASYNC n
        PPP_BSDCOMP n
        PPP_DEFLATE n
        PPP_FILTER n
        PPP_MPPE n
        PPP_MULTILINK n
        PPP_SYNC_TTY n
        PPTP n
        PRISM2_USB n
        QLGE n
        RAVE_SP_CORE n
        REGULATOR_MT6315 n
        REGULATOR_QCOM_LABIBB n
        REGULATOR_QCOM_SPMI n
        REGULATOR_QCOM_USB_VBUS n
        RPCSEC_GSS_KRB5 n
        RTL8192U n
        RTLLIB n
        SATA_ACARD_AHCI n
        SATA_INIC162X n
        SATA_SIL24 n
        SENSORS_APDS990X n
        SENSORS_BH1770 n
        SENSORS_LIS3_I2C n
        SENSORS_TSL2550 n
        SLIMBUS n
        SND_FIREWIRE n
        SPMI_HISI3670 n
        SSB n
        UIO_CIF n
        USB4 n
        USB_C67X00_HCD n
        USB_CDNS_SUPPORT n
        USB_DWC2 n
        USB_DWC3 n
        USB_FOTG210_HCD n
        USB_ISP116X_HCD n
        USB_ISP1760 n
        USB_MUSB_HDRC n
        USB_NET_DRIVERS n
        USB_NET_RNDIS_WLAN n
        USB_OXU210HP_HCD n
        USB_R8A66597_HCD n
        USB_SL811_HCD n
        USB_U132_HCD n
        VGA_SWITCHEROO n
        VIDEO_SOLO6X10 n
        VIDEO_TW5864 n
        VIDEO_TW68 n
        VIDEO_TW686X n
        VMWARE_VMCI n
        VMXNET3 n
        VT6655 n
        WFX n
        XILINX_SDFEC n
    '';
  }];
}
